# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-20 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_flat_obj_apparts1_pr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat_obj',
            name='apparts1_pr',
        ),
    ]
