# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-24 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20181024_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_obj',
            name='pereferiya',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Электричество', 'Электричество'), ('Газ', 'Газ'), ('Канализация', 'Канализация')], default='--', max_length=125, verbose_name='Переферия:'),
        ),
        migrations.AlterField(
            model_name='flat_obj',
            name='vid',
            field=models.CharField(choices=[('На море', 'На море'), ('На горы', 'На горы'), ('На море и горы', 'На море и горы')], default='--', max_length=25, verbose_name='Вид'),
        ),
    ]
