# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-20 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20181003_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_obj',
            name='apparts_pr',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3, verbose_name='Пр.апартаментов'),
        ),
    ]
