# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-15 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvonki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zvonok',
            name='coment',
            field=models.TextField(verbose_name='Коментарий по проделанной работе'),
        ),
        migrations.AlterField(
            model_name='zvonok',
            name='date_sozd',
            field=models.DateTimeField(verbose_name='Дата создания:'),
        ),
        migrations.AlterField(
            model_name='zvonok',
            name='prezvonit',
            field=models.DateTimeField(verbose_name='Перезвонить: '),
        ),
        migrations.AlterField(
            model_name='zvonok',
            name='prim',
            field=models.TextField(verbose_name='Первичная информация:'),
        ),
    ]
